# Generated by Django 4.2.4 on 2023-08-21 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoshipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
