# Generated by Django 4.2.4 on 2023-08-30 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autoshipping", "0002_alter_delivery_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelist",
            name="price",
        ),
    ]
