# Generated by Django 4.2.4 on 2023-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoshipping", "0003_remove_pricelist_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin_code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
