# Generated by Django 4.2.4 on 2023-09-10 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoshipping", "0003_remove_pricelist_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="autoshipping.category",
            ),
        ),
    ]
